# Generated by Django 5.2 on 2025-04-27 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SanitaryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tk', models.CharField(max_length=100, verbose_name='Название (туркм.)')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Название (рус.)')),
            ],
            options={
                'verbose_name': 'Категория сантехники',
                'verbose_name_plural': 'Категории сантехники',
            },
        ),
        migrations.CreateModel(
            name='SanitaryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tk', models.CharField(max_length=200, verbose_name='Название (туркм.)')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Название (рус.)')),
                ('image', models.ImageField(upload_to='sanitaryware/', verbose_name='Изображение')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('material_tk', models.CharField(max_length=100, verbose_name='Материал (туркм.)')),
                ('material_ru', models.CharField(max_length=100, verbose_name='Материал (рус.)')),
                ('dimensions_tk', models.CharField(max_length=100, verbose_name='Размеры (туркм.)')),
                ('dimensions_ru', models.CharField(max_length=100, verbose_name='Размеры (рус.)')),
                ('color_tk', models.CharField(max_length=100, verbose_name='Цвет (туркм.)')),
                ('color_ru', models.CharField(max_length=100, verbose_name='Цвет (рус.)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanitary.sanitarycategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Сантехническое изделие',
                'verbose_name_plural': 'Сантехнические изделия',
            },
        ),
    ]
