# Generated by Django 5.2 on 2025-04-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TileProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Название (рус)')),
                ('name_tk', models.CharField(max_length=100, verbose_name='Название (туркм)')),
                ('image', models.ImageField(upload_to='tiles/', verbose_name='Изображение')),
                ('size_ru', models.CharField(max_length=50, verbose_name='Размер (рус)')),
                ('size_tk', models.CharField(max_length=50, verbose_name='Размер (туркм)')),
                ('color_ru', models.CharField(max_length=50, verbose_name='Цвет (рус)')),
                ('color_tk', models.CharField(max_length=50, verbose_name='Цвет (туркм)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Плитка',
                'verbose_name_plural': 'Плитки',
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
