# Generated by Django 5.2 on 2025-04-27 15:58

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_tileproduct_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tileproduct',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=85, scale=None, size=[800, 800], upload_to='tiles/', verbose_name='Изображение'),
        ),
    ]
