# Generated by Django 5.2 on 2025-04-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('title_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок (рус)')),
                ('preview_ru', models.TextField(blank=True, null=True, verbose_name='Превью (рус)')),
                ('full_text_ru', models.TextField(blank=True, null=True, verbose_name='Полный текст (рус)')),
                ('title_tk', models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок (туркм)')),
                ('preview_tk', models.TextField(blank=True, null=True, verbose_name='Превью (туркм)')),
                ('full_text_tk', models.TextField(blank=True, null=True, verbose_name='Полный текст (туркм)')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
