# Generated by Django 5.2 on 2025-04-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='subject',
            field=models.CharField(choices=[('question', 'Вопрос'), ('order', 'Заказ'), ('cooperation', 'Сотрудничество'), ('other', 'Другое')], default='question', max_length=20),
        ),
    ]
